--Overlay Award
function c511001428.initial_effect(c)
	--Activate
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_ACTIVATE)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetOperation(c511001428.operation1)
	e1:SetHintTiming(0,TIMING_MAIN_END)
	c:RegisterEffect(e1)
	--instant(chain)
	local e2=Effect.CreateEffect(c)
	e2:SetDescription(aux.Stringid(511001428,0))
	e2:SetType(EFFECT_TYPE_QUICK_O)
	e2:SetRange(LOCATION_SZONE)
	e2:SetCode(EVENT_FREE_CHAIN)
	e2:SetHintTiming(0,TIMING_MAIN_END)
	e2:SetCondition(c511001428.condition2)
	e2:SetOperation(c511001428.operation2)
	c:RegisterEffect(e2)
end
function c511001428.filter(c)
	return c:IsFaceup() and c:IsType(TYPE_XYZ)
end
function c511001428.operation1(e,tp,eg,ep,ev,re,r,rp)
	if not e:GetHandler():IsRelateToEffect(e) then return end
	if Duel.GetFlagEffect(tp,511001428)==0 and Duel.GetOverlayCount(tp,1,0)>0 and Duel.IsExistingMatchingCard(c511001428.filter,tp,0,LOCATION_MZONE,1,nil) 
		and Duel.GetCurrentPhase()<=PHASE_BATTLE and Duel.SelectYesNo(tp,aux.Stringid(61965407,0)) then
		local g1=Duel.GetOverlayGroup(tp,1,0)
		local g2=Duel.GetMatchingGroup(c511001428.filter,tp,0,LOCATION_MZONE,nil)
		Duel.Hint(HINT_SELECTMSG,tp,aux.Stringid(47660516,0))
		local mg2=g1:Select(tp,1,1,nil)
		local oc=mg2:GetFirst():GetOverlayTarget()
		Duel.Hint(HINT_SELECTMSG,tp,aux.Stringid(81816475,1))
		local tc=g2:Select(tp,1,1,nil):GetFirst()
		Duel.Overlay(tc,mg2)
		Duel.RaiseSingleEvent(oc,EVENT_DETACH_MATERIAL,e,0,0,0,0)
		local e1=Effect.CreateEffect(e:GetHandler())
		e1:SetType(EFFECT_TYPE_FIELD)
		e1:SetCode(EFFECT_SKIP_BP)
		e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
		e1:SetTargetRange(1,1)
		e1:SetReset(RESET_PHASE+PHASE_END)
		Duel.RegisterEffect(e1,tp)
		Duel.RegisterFlagEffect(tp,511001428,RESET_PHASE+PHASE_END,0,1)
	end
end
function c511001428.condition2(e,tp,eg,ep,ev,re,r,rp)
	return Duel.GetCurrentPhase()<=PHASE_BATTLE and not e:GetHandler():IsStatus(STATUS_CHAINING)
		and Duel.GetFlagEffect(tp,511001428)==0 and Duel.GetOverlayCount(tp,1,0)>0 
		and Duel.IsExistingMatchingCard(c511001428.filter,tp,0,LOCATION_MZONE,1,nil)
end
function c511001428.operation2(e,tp,eg,ep,ev,re,r,rp)
	if not e:GetHandler():IsRelateToEffect(e) then return end
	local g1=Duel.GetOverlayGroup(tp,1,0)
	local g2=Duel.GetMatchingGroup(c511001428.filter,tp,0,LOCATION_MZONE,nil)
	Duel.Hint(HINT_SELECTMSG,tp,aux.Stringid(47660516,0))
	local mg2=g1:Select(tp,1,1,nil)
	local oc=mg2:GetFirst():GetOverlayTarget()
	Duel.Hint(HINT_SELECTMSG,tp,aux.Stringid(81816475,1))
	local tc=g2:Select(tp,1,1,nil):GetFirst()
	Duel.Overlay(tc,mg2)
	Duel.RaiseSingleEvent(oc,EVENT_DETACH_MATERIAL,e,0,0,0,0)
	local e1=Effect.CreateEffect(e:GetHandler())
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_SKIP_BP)
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e1:SetTargetRange(1,1)
	e1:SetReset(RESET_PHASE+PHASE_END)
	Duel.RegisterEffect(e1,tp)
	Duel.RegisterFlagEffect(tp,511001428,RESET_PHASE+PHASE_END,0,1)
end
