--Turn Jump
function c511000091.initial_effect(c)
	--Activate
	local e1=Effect.CreateEffect(c)
	e1:SetCategory(CATEGORY_DESTROY)
	e1:SetType(EFFECT_TYPE_ACTIVATE)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetHintTiming(TIMING_BATTLE_START,0)
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e1:SetCondition(c511000091.condition)
	e1:SetOperation(c511000091.operation)
	c:RegisterEffect(e1)
end
function c511000091.condition(e,tp,eg,ep,ev,re,r,rp)
	return Duel.GetCurrentPhase()==PHASE_BATTLE and not Duel.CheckPhaseActivity() and Duel.GetCurrentChain()==0
end
function c511000091.operation(e,tp,eg,ep,ev,re,r,rp)
	if Duel.GetTurnPlayer()==tp then 
	Duel.SkipPhase(tp,PHASE_DRAW,RESET_PHASE+PHASE_END,4)
	Duel.SkipPhase(tp,PHASE_MAIN1,RESET_PHASE+PHASE_END,4)
	Duel.SkipPhase(tp,PHASE_BATTLE,RESET_PHASE+PHASE_END,2,2)
	Duel.SkipPhase(tp,PHASE_MAIN2,RESET_PHASE+PHASE_END,2)
	Duel.SkipPhase(1-tp,PHASE_DRAW,RESET_PHASE+PHASE_END,3)
	Duel.SkipPhase(1-tp,PHASE_MAIN1,RESET_PHASE+PHASE_END,3)
	Duel.SkipPhase(1-tp,PHASE_BATTLE,RESET_PHASE+PHASE_END,3,3)
	Duel.SkipPhase(1-tp,PHASE_MAIN2,RESET_PHASE+PHASE_END,3)
	local e1=Effect.CreateEffect(e:GetHandler())
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_CANNOT_BP)
	e1:SetTargetRange(1,1)
	e1:SetReset(RESET_PHASE+PHASE_END,6)
	Duel.RegisterEffect(e1,tp)
	elseif Duel.GetTurnPlayer()~=tp then
	Duel.SkipPhase(1-tp,PHASE_DRAW,RESET_PHASE+PHASE_END,4)
	Duel.SkipPhase(1-tp,PHASE_MAIN1,RESET_PHASE+PHASE_END,4)
	Duel.SkipPhase(1-tp,PHASE_BATTLE,RESET_PHASE+PHASE_END,2,2)
	Duel.SkipPhase(1-tp,PHASE_MAIN2,RESET_PHASE+PHASE_END,2)
	Duel.SkipPhase(tp,PHASE_DRAW,RESET_PHASE+PHASE_END,3)
	Duel.SkipPhase(tp,PHASE_MAIN1,RESET_PHASE+PHASE_END,3)
	Duel.SkipPhase(tp,PHASE_BATTLE,RESET_PHASE+PHASE_END,3,3)
	Duel.SkipPhase(tp,PHASE_MAIN2,RESET_PHASE+PHASE_END,3)
	local e1=Effect.CreateEffect(e:GetHandler())
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_CANNOT_BP)
	e1:SetTargetRange(1,1)
	e1:SetReset(RESET_PHASE+PHASE_END,6)
	Duel.RegisterEffect(e1,tp)
	end
end
